version: 2

env:
  - CONTAINER_REGISTRY={{ if index .Env "CONTAINER_REGISTRY" }}{{ .Env.CONTAINER_REGISTRY }}{{ else }}ghcr.io/jacobweinstock{{ end }}

before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
      - amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
release:
  disable: "{{ if index .Env \"GITHUB_TOKEN\" }}false{{ else }}true{{ end }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers_v2:
  - images:
      - "{{ .Env.CONTAINER_REGISTRY }}/waitdaemon"
    tags:
      - "{{ .Version }}"
      - latest
      - "{{ if index .Env \"CUSTOM_TAG\" }}{{ .Env.CUSTOM_TAG }}{{ end }}"
    dockerfile: Dockerfile.goreleaser
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
